-- CREATE TABLE some_table (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     some_field VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- );

